### ISSUE TITLE
eix is not reading new versions of some packages.

### ISSUE THREAD

**Issue by kurumushi** [vaeth/eix#10]
Recently I've noticed that eix is not picking up newer versions of some packages. For example The newest version of gentoo-sources in portage is 4.1.6. emerge finds it fine, and installs, but if I do 'eix  gentoo-sources' It correctly reads my installed version, but it shows the newest available version as 4.1.4.

I've tried eix-update, eix-sync, deleting the eix database and creating it again. Still the same problem persists.

**Comment by vaeth** [comment]
Which sync method are you using?
Have you perhaps switched to git syncing recently? In this case you have to rebuild the cache with egencache, since portage does not do this for you. Set up e.g. a corresponding /etc/portage/postsync.d hook.

**Comment by vaeth** [comment]
I meant /etc/portage/repo.postsync.d

**Comment by kurumushi** [comment]
I'm using funtoo, so I've been git syncing for years. This only started about a week or so ago.

**Comment by voidzero** [comment]
I'm seeing this issue too. Example: app-crypt/xca-1.3.0 does not show, only version 1.1.0 shows but both are in /usr/portage/app-crypt/xca...

**Comment by vaeth** [comment]
Very likely this is not a problem of eix but of emerge --sync (or whatever your update command is) not updating the metadata properly.
In the default configuration, eix does not read the ebuild but the metadata, i.e. in the above example, you should check whether the corresponding files /usr/portage/metadata/md5-cache/app-crypt/xca-* do exist and have a reasonable content.
If yes, then it might be an eix issue. If no, you have to call egenchache with appropriate arguments (and do so after every syncing in an repo.postsync.d hook). If calling egencache does not produce the files, it might be a portage bug.

**Comment by voidzero** [comment]
Ah, indeed, seems you're right: there is no xca-1.3.0 file in that directory. `egencache --update app-crypt/xca` created it, and then an `eix-update` was enough to get eix to recognise it.

I'll run egencache --update without arguments to regenerate the cache for all packages.

It seems that they have added .gitignore files to the portage tree recently, I'll check with the Funtoo developers.

Thank you @vaeth. :+1:

**Comment by kurumushi** [comment]
Yes, it appears that for some reason emerge --sync is selectively not creating some of these files. Thanks for pointing out where the problem was. I think this can be closed.
