### ISSUE TITLE
eix-test-obsolete: Feature request to --clean obsolete entries

### ISSUE THREAD

**Issue by Massimo-B** [vaeth/eix#100]
Hello mv,

are there any plans to implement some `--clean` option for the `eix-test-obsolete` script?
You could generate update files that could be merged or cherry-picked via etc-update later, just like portage does. That would be great.

Maybe also think about additionally supporting long options like `--help` instead of `-h` only, to be consistent with eix. And I would consider moving the manual into a separated man-page because it's a separated executable. Right now the supported options are not considered in `man eix`.

Best regards.

**Comment by vaeth** [comment]
There will never be a `--clean` option. This is not how `eix-test-obsolete` works. It is package based and not based on /etc/portage/packkage.* entries.

Also, `eix-test-obsolete` is a (POSIX) shell script; long options are not natively supported by POSIX, and I won't write a manual option parsing in POSIX shell only to support long options.

Concerning the man-page, there is chaos anyway. I strive to keep everything documented here which is not documented elsewhere, but that's it.
