### ISSUE TITLE
Ability to hide updates that change only ebuild revision in eix-diff

### ISSUE THREAD

**Issue by annulen** [vaeth/eix#101]
It would be great if eix-diff would have a mode where only updates which change package version are shown, ignoring updates that only change ebuild revision.

**Comment by vaeth** [comment]
That would require a major rewrite of how versions are handled internally by eix. Moreover, I do not consider the feature that useful: No matter whether it is an upstream (version) or downstream (revision) bump, it can always be important and even security related.
