### ISSUE TITLE
eix-test-obsolete should tolerate */* and cat/* in package.license

### ISSUE THREAD

**Issue by jonasstein** [vaeth/eix#102]
# Example
`/etc/portage/package.license/package.license` contains

    media-fonts/* bh-luxi
    */*PUEL

then we will get a warning for each available package which does require this license setting.

```
Not installed but in /etc/portage/package.license:
...
[N] media-fonts/font-arabic-misc (1.0.3-r2): X.Org arabic bitmap fonts
Found 197 matches
Only 50 matches displayed on terminal
Set EIX_LIMIT=0 to show all matches

```

# Solution 
eix-test-obsolete should not warn if someone accepts a license in general (with `*`)

`echo "*/* $(cpuid2cpuflags)" > /etc/portage/package.use/00cpu-flags` as explained in https://wiki.gentoo.org/wiki/CPU_FLAGS_X86
does not trigger eix-test-obsolete warnings too.

**Comment by vaeth** [comment]
Marking uninstalled packages is what eix by default is configured to consider as redundancy:
```
REDUNDANT_IF_IN_LICENSE="-some"
```
For  package.use this is not the case:
```
REDUNDANT_IF_IN_USE="false"
```
It is up to you to change this default (e.g. in a file in /etc/eixrc) if you want to have the same behavior as for package.use:
```
REDUNDANT_IF_IN_LICENSE="false"
```
