### ISSUE TITLE
Include remote-id URls in HOMEPAGE or other field in `eix` output

### ISSUE THREAD

**Issue by thesamesam** [vaeth/eix#105]
`eix` currently shows `HOMEPAGE` but not `<remote-id>` elements (https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Upstream_remote-id_types) from `metadata.xml`:
```
$ eix minicoredumper
* sys-process/minicoredumper
     Available versions:  (~)2.0.1-r1 (~)2.0.2
     Homepage:            https://linutronix.de/minicoredumper
     Description:         Core dump file processor
```

It'd be neat if it could include various remote-ids with the corresponding URLs to allow easily getting to e.g. corresponding github repos.

See also https://bugs.gentoo.org/877519.

**Comment by krushia** [comment]
I'd like to broaden the scope of this bug to include all `<upstream/>` elements. This includes `<maintainer>`, `<changelog>`, `<doc>`, `<bugs-to>`, and `<remote-id>`. As a lazy user I find `<bugs-to>` to be very handy.

https://www.gentoo.org/glep/glep-0068.html#upstream-descriptions
https://devmanual.gentoo.org/ebuild-writing/misc-files/metadata/

**Comment by vaeth** [comment]
Won't fix: eix does not store or read metadata.xml, and there is no intention to do so.
The HOMEPAGE data is taken from the ebuild.

**Comment by vaeth** [comment]
The eix scope is even more limited than ebuild files: The scope of its database is essentially limited to portage metadata of the ebuild (actually even to a subset thereof) - the data which you find in $REPO/metadata/md5-cache or in the sqlite database of portage. The feature might be reconsidered if (but only if) parts of metadata.xml will be made available by portage in this metadata.
