### ISSUE TITLE
eix -r/--regex option should be case-sensitive by default

### ISSUE THREAD

**Issue by flexibeast** [vaeth/eix#110]
i created [a bug on b.g.o for this](https://bugs.gentoo.org/907276), but josef64 on #gentoo suggested i open an issue here.

Someone on #gentoo was wondering how to do a case-sensitive search with eix. It turns out that `-e --substring` is the answer, but i was surprised to find that the `-r`/`--regex` option is case-insensitive, with (i believe) no way of changing this. The standard behaviour of regex implementations is to be case-sensitive unless specified otherwise (e.g. via `/i` in Perl), so i believe eix's behaviour in this regard violates the principle of least surprise.

**Comment by vaeth** [comment]
eix-0.36.7 has a  new --regex-case option, and this option is chosen by default if normally a regex would be the default, but the pattern contains an uppercase character.
