### ISSUE TITLE
eix-diff should highlight update of sys-apps/portage whenever it's available

### ISSUE THREAD

**Issue by annulen** [vaeth/eix#112]
`emerge --sync` prints bold notification "An update to portage is available..." if there's an update for `sys-apps/portage`. However, when syncing with `eix-sync` this message is easy to overlook because of `eix-diff` output being printed afterwards. I suggest that `eix-diff` itself should make a line with `sys-apps/portage` more visually distinctive (e.g. colorize it) whenever update is avialable.

**Comment by vaeth** [comment]
There is nothing special about the package `sys-apps/portage`. At most for portage itself an update of that package means something. Highlighting random packages is not the task of eix. If you want, you can configure it yourself (e.g. by checking the return value of eix -ue sys-apps/portage and printing something or by modifying the DIFF_FORMAT_CHANGED_VERSIONS to print something else for sys-apps/portage).
