### ISSUE TITLE
White background support 

### ISSUE THREAD

**Issue by denisstrizhkin** [vaeth/eix#117]
![image](https://github.com/vaeth/eix/assets/57726946/c6fc36aa-9cfe-4790-84cb-ca2374bd02d4)

All text still renders as white on black.

**Comment by vaeth** [comment]
Your terminal should set `COLORFGBG` appropriately; if not, you have to do it.
For details, look for `DARK`, `TERM_DARK`, `COLORFGBG_DARK` in `man eix`.
