### ISSUE TITLE
wrong installation time reported

### ISSUE THREAD

**Issue by leapfog** [vaeth/eix#119]
according to the manpage, the command

`eix '-I*' --format '<installedversions:DATESORT>' | sort -n | cut -f2-3`

should list installed packages, sorted by installation time.

Unfortunately that isn't true when a package has been installed with

`emerge --getbinpkg y`

**Comment by vaeth** [comment]
The manpage refers for eix-installed to `CHECK_INSTALLED_OVERLAYS` and `USE_BUILD_TIME`. With the latter variable, you can configure which time to use (cf. manpage).

**Comment by leapfog** [comment]
Yes, setting `USE_BUILD_TIME=false` indeed solved my problem. But when not reading the _whole_ manpage, that comes with a bit of a surprise. Maybe a hint could be added to that example, pointing the user to `USE_BUILD_TIME`.
