### ISSUE TITLE
"eix-sync -q" not quiet when gentoo tree has not changed

### ISSUE THREAD

**Issue by hannob** [vaeth/eix#120]
Subject says it already, to reproduce, just run "eix-sync -q" twice. First time it'll be quiet, second time it produces an output.

```
$ eix-sync -q
$ eix-sync -q
 * Main gentoo tree does not appear to have changed: exiting
 * Use -a or set have_changed=: in a ! hook to override this check
```

Given that this is not an error, I don't think this should produce any output in quiet mode.

**Comment by vaeth** [comment]
The exit due to the non-change is considered an error. It also yields a nonzero exit code.
Indeed, it would be very strange if the above unexpected behavior (of e.g. not updating overlays) would not be reported.
