### ISSUE TITLE
Explicit license for eix.proto & generated files

### ISSUE THREAD

**Issue by wwjjbb** [vaeth/eix#122]
**eix/src/output/eix.proto** 

The license for this file is not explicitly stated, but it's probably reasonably safe to assume GPL2(only) as for the eix project.

It impacts the status of the generated files because the license for protobuf (https://github.com/protocolbuffers/protobuf/blob/main/LICENSE) states: "Code generated by the Protocol Buffer compiler is owned by the owner
of the input file used when generating it.". So their status is a bit fluffy too.

Please add a copyright header to the proto file just to make it official.

While you're there, could there be a linking exception for this file, "GPL2 or later", just to make the use a little easier with other variations of GPL?

**Comment by vaeth** [comment]
Will be fixed in eix-0.36.9
