### ISSUE TITLE
printing of package versions available only from an overlay

### ISSUE THREAD

**Issue by efferre79** [vaeth/eix#124]
I would like to print a list of packages installed from a specific overlay. The list must include only the installed package versions coming from the specific overlay, the output should not contains all the versions installed from gentoo or other overlays.

If I use this command

`eix --in-overlay REPO  --format '<installedversions:NAMEVERSION>'`

then all the versions are printed even if not present in the specified overlay REPO. So I thought of using the conditional formatting:

`eix --in-overlay REPO  --format '{overlaykey=REPO}<installedversions:NAMEVERSION>{}'`

but it doesn't seem to work.

**Comment by efferre79** [comment]
That helps but only if I specify a pattern, with an empty pattern I get no result.

**Comment by vaeth** [comment]
I cannot reproduce this here. Maybe you have some nonstandard default options set for eix: Does omitting the `--format` (and its argument) output something if you do not specify a pattern?
In any case, specifying `-r` (searching for an empty regular expression) should work.

**Comment by efferre79** [comment]
If I omit `--format` I get the list of packages. But when using `--format` I get **No matches found** (even if I use `-r`). I am using version 0.36.7-r1, latest in portage.

**Comment by vaeth** [comment]
Sorry, I cannot reproduce this.

**Comment by efferre79** [comment]
The only thing I get is a list of 5 overlays:

[1] "REPO1" /path/to/repo1
[1] "REPO1" /path/to/repo1
[1] "REPO1" /path/to/repo1
[1] "REPO1" /path/to/repo1

**Comment by vaeth** [comment]
Oh, you did not see that I fixed a typo in my first reply.

**Comment by efferre79** [comment]
good catch, now it works like a charm! Thanks for the help! I would suggest to add this example in the manual, I think it might be useful to other people

**Comment by vaeth** [comment]
There are so many examples some people find useful, and the manpage is already more than long enough.
