### ISSUE TITLE
eix interprets AMDGPU_TARGETS as AMDGPU USE_EXPAND variables

### ISSUE THREAD

**Issue by equaeghe** [vaeth/eix#128]
The USE_EXPAND variables with AMDGPU_TARGETS are interpreted by eix as AMDGPU variables. For example, for `caffe2` I get

```
# eix caffe2
[I] sci-libs/caffe2
     Available versions:  ~2.4.0-r1^t ~2.4.1-r4^t (~)2.5.1-r7^t {cuda distributed fbgemm flash gloo mkl mpi nnpack +numpy onednn openblas opencl openmp qnnpack rocm xnnpack AMDGPU="+targets_gfx90a targets_gfx803 targets_gfx900 +targets_gfx906 +targets_gfx908 targets_gfx940 targets_gfx941 +targets_gfx942 targets_gfx1010 targets_gfx1011 targets_gfx1012 +targets_gfx1030 targets_gfx1031 +targets_gfx1100 targets_gfx1101 targets_gfx1102" PYTHON_SINGLE_TARGET="python3_10 python3_11 python3_12"}
[…]
```

**Comment by vaeth** [comment]
Not reproducible here:

```
% eix caffe2 
* sci-libs/caffe2
     Available versions:  ~2.4.0-r1^t ~2.4.1-r4^t ~2.5.1-r7^t {cuda distributed fbgemm flash gloo mkl mpi nnpack +numpy onednn openblas opencl openmp qnnpack rocm xnnpack AMDGPU_TARGETS="+gfx90a gfx803 gfx900 +gfx906 +gfx908 gfx940 gfx941 +gfx942 gfx1010 gfx1011 gfx1012 +gfx1030 gfx1031 +gfx1100 gfx1101 gfx1102" PYTHON_SINGLE_TARGET="python3_10 python3_11 python3_12"}
```

I assume that you either have overridden some environment variable or include a respository/profile which sets AMDGPU in either `USE_EXPAND` or `USE_EXPAND_HIDDEN`.

**Comment by equaeghe** [comment]
> I assume that you either have overridden some environment variable or include a respository/profile which sets AMDGPU in either `USE_EXPAND` or `USE_EXPAND_HIDDEN`.

I'm stumped… I wouldn't know what would cause this. Nowhere in `/etc` is AMDGPU mentioned in a way that could seem to cause this:
```
$ sudo grep -R AMDGPU /etc/*
/etc/portage/package.use/general:sci-libs/caffe2 AMDGPU_TARGETS: -*
/etc/portage/package.use/general:llvm-runtimes/openmp LLVM_TARGETS: AMDGPU
```

**Comment by vaeth** [comment]
You have to check the profiles. There is one specified by make.profile, but others also inside your repositories (specified in repos.conf), and there might be includes of further ones inside of profiles, or their locations can also be specified by some variables. Also overrides of variables by other variables (e.g. environment variables) are possible.

**Comment by equaeghe** [comment]
> You have to check the profiles. There is one specified by make.profile, but others also inside your repositories (specified in repos.conf), and there might be includes of further ones inside of profiles, or their locations can also be specified by some variables. Also overrides of variables by other variables (e.g. environment variables) are possible.

Thanks. I tried finding the culprit, but failed. In any case, I am convinced `eix` is not at fault, so I am closing this.
