### ISSUE TITLE
Weird output of $myvarcmd

### ISSUE THREAD

**Issue by sint** [vaeth/eix#13]
When running eix-sync (everything else is ok) the first line of output always is:

**Running $myvarcmd**

I have this problem on all my systems. In /etc/eixrc/00-eixrc i've only change some coloring:

COLOR_INST_VERSION="white,1;blue|33,1;%{BG1}|black;green|30,1;%{BG3}"

BG0=none;
BG1=none;
BG2=none;
BG3=none;

COLORSCHEME0=0;
COLORSCHEME1=0;
COLORSCHEME2=0;
COLORSCHEME3=0;

Otherwise eix is running fine.

**Comment by vaeth** [comment]
Which version?
This was a regression of eix-0.30.11 and should have be fixed in eix-0.31.0...

**Comment by sint** [comment]
I see, thanks. I have eix stable running, which is eix-0.30.11. Since its not doing any harm, i'll wait until 0.31 becomes stable.

**Comment by sint** [comment]
Is there any ETA on 0.31 becoming stable?

**Comment by vaeth** [comment]
It depends on whether further serious bugs are reported: There were some essential bugfixes in the previous releases, so I would like to stabilize the most current one (0.31.7-r1). However, this is rather recent, so we have to wait at least 1-2 months. I recommend to use that version even if in ~ARCH, currently.
