### ISSUE TITLE
Invalid "invalid line in /etc/portage/sets" warning

### ISSUE THREAD

**Issue by flussence** [vaeth/eix#20]
I get the following every time I run eix-sync on one box:

    -- invalid line 4 in /etc/portage/sets/localhost: "<dev-php/pecl-yaml-2.0[php_targets_php5-5]"
        operator without a version part

I think the parser's getting confused by the hyphen in the USE dependency when looking for a version part, because that's the only line it complains about in the full file:

    <dev-lang/php-5.6[crypt,filter,json,pdo,postgres]
    dev-php/pecl-apcu[php_targets_php5-5]
    dev-php/pecl-http[php_targets_php5-5]
    <dev-php/pecl-yaml-2.0[php_targets_php5-5]

**Comment by vaeth** [comment]
The issue should be fixed in current eix git master (>=eix-0.31.7).
However, I think that specifying USE-flags in sets does not make much sense (I am surprised that portage accepts it at all): You have to specify these USE-flags in package.use (or globally in make.conf).
