### ISSUE TITLE
Searching for numbers

### ISSUE THREAD

**Issue by devurandom** [vaeth/eix#22]
eix is unable to search for numbers:
```
# eix -c 264
No matches found
# eix -c x264
[I] media-libs/x264 (0.0.20151011@17/10/15): A free library for encoding X264/AVC streams
[I] media-plugins/gst-plugins-x264 (1.6.3(1.0)@02/02/16): plugin for gstreamer
[I] media-plugins/mediastreamer-x264 (1.4.2-r1@24/08/15): mediastreamer plugin: add H264 support
[N] media-video/x264-encoder ((~)0.0.20151011): A free commandline encoder for X264/AVC streams
Found 4 matches
```

The result is independent of the `--compact` switch. It also happens with `--description`.

**Comment by vaeth** [comment]
Not a bug: If you do not specify match fields and match algorithm, a pure number chooses by default --eapi and --exact, i.e. your above query matches for packages with the EAPI 264 (which do not exist).
Specify e.g. eix -csz 264 to make sure you want to look for substrings (-z) in package names (-s).
