### ISSUE TITLE
Update a single repository

### ISSUE THREAD

**Issue by NP-Hardass** [vaeth/eix#23]
While I'm working heavily in one of my repos, I find it helpful to update eix so I can query it as I keep working.  Unforuntately, when I do so, eix updates every repository.  So, the goal is update just one repository out of the list of repositories.

I thought maybe I could achieve this with  -x "*" -a "someoverlay"  but the -x overrides the -a.
So, firstly, is there a better way to achieve this?  And secondly, do you think that -a should occur after/override -x?

**Comment by vaeth** [comment]
The list of excluded overlays (which is also fetched from environment variables, not only from -x) is always applied to the list of all overlays (which is constructed with many tools).

In theory, you could do

```PORTAGE_REPOSITORIES=" " eix-update -a ...```

but this won't work, because eix-update needs to know the main repository e.g. to find out the available categories. So, in practice, you need to specify a "default" PORTAGE_REPOSITORIES. If you configure your main/local repository in separate files each, you can do

```PORTAGE_REPOSITORIES=`cat /etc/repos.conf/your-main-repo.conf /etc/repos.conf/your-local-repo.conf` eix-update -x /usr/portage/```

If you don't, you can do something like

```
PORTAGE_REPOSITORIES="[gentoo]
location = /usr/portage" eix-update -x /usr/portage/ -a ...
```

**Comment by NP-Hardass** [comment]
Unfortunately, this saves just the repository specified with -a to the cache file.    I was hoping it would update only the specified repo and leave the rest as they are.  Guess I should make that into a feature request?

**Comment by vaeth** [comment]
> Unfortunately, this saves just the repository specified with -a to the cache file

I thought that is what you wanted.
So what you want is that during eix-update the data of most overlays (with one exception) is read from the original file. This can be managed by changing the cache-method for these overlays to the type "eix::[overlay-path]"

Roughtly speaking you have to call something like

``eix-update -m /usr/portage/ eix -m /usr/portage/layman/foo eix::/usr/portage/layman/foo -m /usr/portage/layman/bar eix::/usr/local/layman/bar``

which means that for the repositories /usr/portage, /usr/portage/layman/foo, and /usr/portage/layman/bar the data is not read from the overlay but instead from the eix cache-file, using there the corresponding overlay.

As an example how to build the -m [foo] [bar] arguments automatically, you can look at the /usr/bin/eix-layman script, in particular the function "AddLocalMethods()" from /usr/bin/eix-functions.sh

**Comment by vaeth** [comment]
Closing, since I think there is nothing to be fixed in eix for this
