### ISSUE TITLE
Select packages based on install date

### ISSUE THREAD

**Issue by bircoph** [vaeth/eix#26]
Hello,

it would be nice to have an ability to select packages based on their install date, e.g.
  --installed-after < $date | PKG >
  --installed-before < $date | PKG >
where PKG is usual [category/]name[-version|

It will be very useful for cases where emerge says "please rebuild all packages using this one", e.g. due to ABI change after python or gcc update:
   revdep-rebuild --library 'libstdc++.so.6' -- --exclude gcc
will result into massive package rebuild, though in case of \@world update obviously there is no need to rebuild packages built after the latest gcc was enabled as a default compiler. Otherwise a lot of time will be wasted.

It is possible to do this kind of selection right now, e.g. with
  eix '-I*' --format '<installedversions:DATESORT>' | sort -n
and then cutting that file according to required date limit and feeding selected files to emerge, but it will be much more convenient to have native options for such operations.

**Comment by vaeth** [comment]
The eix-installed-after script does already all what you require.

**Comment by bircoph** [comment]
Hi!
Somehow I missed this script, thanks for pointing it out.

However, it doesn't allow me to do exactly what I need: I need to apply install date filter together with other filters (e.g. -C dev-python --installed-after ...). Of course this can be fixed by either modifying script (-I* selector) or post-processing of the output.

**Comment by vaeth** [comment]
Perhaps the script should be modified to allow adding additional eix options on the command line.
However, to handle arguments correctly some magic with push etc. would be necessary which would make the script less readable. (After all, it is the purpose of this script to be a demo how to "program" with eix.) So I am not decided yet what to do.

Your alternative suggestion - to add a time selector to the eix binary - has the problem that such a selector would naturally only apply to packages and thus give difficulties if several slots are installed. To distinguish slots, one would have to provide an attribute with arguments (for the output of installed versions). This is again rather clumsy to use and does not simplify things a lot from the user's perspective. (Apart from the difficulties how to specify times, and that attributes with arguments are rather clumsy to implement.) So I am also hesitating to implement this improvement.

**Comment by bircoph** [comment]
I understand your reasoning.

For now I modified the example script to suit my needs.
So I suppose the issue can be fixed.
