### ISSUE TITLE
eix-sync fails without colors due to set -u

### ISSUE THREAD

**Issue by embe** [vaeth/eix#27]
eix-sync from commit 4806616 fails when run with colors disabled, e.g. when the standrad output is not a terminal:
```
# eix-sync | cat 
/usr/bin/eix-functions.sh: line 125: eixf_good: unbound variable
/usr/bin/eix-functions.sh: line 125: eixf_good: unbound variable
```

**Comment by vaeth** [comment]
Thanks for the report. Should be fixed now.

**Comment by embe** [comment]
It works now.
One minor problem: the last letter of my last name is missing in the ChangeLog :)
