### ISSUE TITLE
eix no more shows up-to-date package versions 

### ISSUE THREAD

**Issue by ujuj** [vaeth/eix#33]
For some reason eix no more shows proper available version of packages on my machine. (Installed version is indicated properly in installation version line though).
Incremental run of eix-update does not help.
Version app-portage/eix-0.32.1-r1.

I don't think it's related but eix-remote update is not capable to reach dev.gentooexperimtal.org for cache of experimental repositories anymore.
I also use layman for adding specific repositories.

**Comment by vaeth** [comment]
A wrong database usually means that you have wrong metadata. Do you perhaps use git and do not update metadata correctly, see issue #18?

**Comment by ujuj** [comment]
I figured it out.
I use rsync, not git and portage ta are correct.

It was the remote.eix which was causing the problem. The new one is not being downloaded and for some reason eix gets it completely wrong with the old one being in the tree (e.g. not showing even the one which is present in normal portgae tree.)
Setting REMOTE_DEFAULT=0 fixed the problem until nex remote.eix is available  I guess.
