### ISSUE TITLE
`eix 389` do not yield net-nds/389-ds-base

### ISSUE THREAD

**Issue by hexum** [vaeth/eix#40]
Type `eix 389`
Expected: `net-nds/389-ds-base`
Actual: None

**Comment by vaeth** [comment]
Which eix are you using?
Previous eix versions defaulted to match field/algorithm --eapi --exact when the query was a pure number. Try eix --name --regex 389
In eix-0.32.8 the heuristics to determine default match field/algorithm was improved and reworked to be less aggressive.

**Comment by hexum** [comment]
Regex match works as expected.
`eix --name --regex 389`

Undesired behaviour was detected on version 0.32.1
```bash
eix -V
0.32.1```

Can't reproduce with latest version.
```
eix -V
0.32.9```

Sorry for disturbing.
