### ISSUE TITLE
0.33.0 Command not found errors

### ISSUE THREAD

**Issue by lehitoskin** [vaeth/eix#44]
I just updated to version 0.33.0 on amd64 Gentoo and I come up with these troubling errors:

```
~> sudo eix-sync
/usr/bin/eix-sync: line 22: ReadFunctions: command not found
/usr/bin/eix-sync: line 24: ReadVar: command not found
/usr/bin/eix-sync: line 25: ReadVar: command not found
/usr/bin/eix-sync: line 26: ReadVar: command not found
/usr/bin/eix-sync: line 27: ReadVar: command not found
```

Downgrading to 0.32.10 allows eix to operate properly.

**Comment by vaeth** [comment]
This is a gentoo downstream bug, because they insist on installing eix-functions.sh such that it does not work as intended. Meanwhile they fixed it such that at least eix-sync works despite their broken installation.

**Comment by lehitoskin** [comment]
Word
