### ISSUE TITLE
eix recolors background

### ISSUE THREAD

**Issue by owenthewizard** [vaeth/eix#45]
When searching for packages with `eix -s`, the background color is set on the printed text. This is unsightly when using f.e. a transparent terminal. See image for details.
![eix](https://user-images.githubusercontent.com/7953513/31579523-bdd85b4e-b0fd-11e7-9252-bb1b7300daff.png)

**Comment by vaeth** [comment]
man eix /FAQ (particularly 2. in the description of color problems)
See also the description of the COLORSCHEME variables on the manpage

**Comment by owenthewizard** [comment]
Thank you.
