### ISSUE TITLE
ReadFunctions: command not found when using eix-sync

### ISSUE THREAD

**Issue by shiznix** [vaeth/eix#46]
eix-0.33.0

~ # eix-sync 
/usr/bin/eix-sync: line 22: ReadFunctions: command not found
/usr/bin/eix-sync: line 24: ReadVar: command not found
/usr/bin/eix-sync: line 25: ReadVar: command not found
/usr/bin/eix-sync: line 26: ReadVar: command not found
/usr/bin/eix-sync: line 27: ReadVar: command not found
/usr/bin/eix-sync: line 28: local_portage_configroot: unbound variable

If I downgrade back to eix-0.32.10 then all is well and eix-sync functions again.

Using eix-0.33.0 it works after changing line 17 from:
`cat "/usr/share/eix/eix-functions.sh"`
to read
`cat "/usr/share/eix/eix-functions"`

Same also for /usr/bin/eix-remote...
 * eix-remote add1
/usr/bin/eix-remote: line 17: ReadFunctions: command not found
/usr/bin/eix-remote: line 22: Push: command not found
/usr/bin/eix-remote: line 23: Push: command not found
/usr/bin/eix-remote: line 24: opt: unbound variable

**Comment by vaeth** [comment]
dupe of https://github.com/vaeth/eix/issues/43

**Comment by shiznix** [comment]
Oops...apologies and thanks.

Seems Gentoo have fixed their ebuild in commit 393761e7afeb26705f164c30a20818f1f951c733

Closing now...
