### ISSUE TITLE
0.32.9: permanent repository index, possible?

### ISSUE THREAD

**Issue by lkraav** [vaeth/eix#53]
Hi. Every time repository indexes change due to repo list management operations, `eix-diff` produces potentially a massive amount of noise moving (re-indexing) packages from index 4 => 5, etc.

I've been thinking about whether it's possible to somehow avoid this.

Because screen estate is quite valuable in text-only output, numeric repository indexes probably can't go away.

Could `eix` somehow maintain a "permanent" index of repositories? If a repository is added at index 5, it should stay index 5 forever, even if there's a hole at index 4 due to repository removal. There are additional complexity use cases to consider here (is it possible to ever re-fill index 4, why, or why not?)

Thoughts?

**Comment by vaeth** [comment]
repository index changes do not happen from nowhere:
You have changed the portage configuration to get such a change, in general.
Simply call manually eix-update after each such change, and after you next syncing eix-diff should display correctly.

**Comment by lkraav** [comment]
I'm not claiming "nowhere" at all. Yes, portage configuration is changed. I would still like `eix` to keep specific index numbers for specific repos.

One thing I'm not sure about: is this maybe a `portage` level issue instead?

**Comment by vaeth** [comment]
> Portage level issue

The order of the repositories (under portage as well as eix) is determined by the value of the `priority` settings. For instance, if you set in /etc/portage/repos.conf/ for a certain repository the value
`priority = 5000`, this will be numbered by eix after the repository with `prority = 2000` (and indeed, the repository with larger priority number is “later” in the sense that if both repositories contain the same (stable unmasked) ebuild, the one with the larger priority number will be installed by portage).

**Comment by lkraav** [comment]
Thaks for the insight. I'll try working this out purely with portage priorities and report back then.

**Comment by vaeth** [comment]
Assuming it works. Please reopen if it does not.
