### ISSUE TITLE
Broken links in manpage

### ISSUE THREAD

**Issue by scottfurry** [vaeth/eix#58]
Manpage, [srcroot]/manpage/en-eix.1.in (and translations) contains links to Gentoo Wiki as 'http://gentoo-wiki.info/'. This appears to be a broken link as page times out. Problem is limited to section regarding sqlite as cached backend(3 links total).

**Comment by vaeth** [comment]
Unfortunately, these pages were lost when the wiki had been lost some years ago.
I doubt that somebody has written new versions since then, so it is impossible to "repair" the links.
I will certainly not rewrite the whole articles to fix this bug.

**Comment by scottfurry** [comment]
I hadn't seen any bug reports on these possible broken links. Unfortunate that information gets lost like this. Closest I could get to topic was this link:
https://wiki.gentoo.org/wiki//etc/portage/modules

**Comment by vaeth** [comment]
The gentoo wiki had a strange history with being lost, restored from google history, officially being abandoned by gentoo, etc.
I found now another link (and also added the one you mentioned above in case that breaks again).
