### ISSUE TITLE
linker errors on Cygwin due to -mindirect-branch=thunk compiler flag

### ISSUE THREAD

**Issue by haubi** [vaeth/eix#64]
Building `app-portage/eix-0.33.7` on `x86_64-pc-cygwin` using `Gentoo Prefix` does fail with the linker errors below. It turns out that the culprit is the `-mindirect-branch=thunk` compiler flag, independent of whether using `sys-devel/gcc-8.3.0` and `sys-devel/binutils-2.32-r1` or Cygwin host's `gcc-7.4.0-1` and `binutils-2.31.1-1`.

As far as I understand, there is the `MV_ADDFLAGS` m4 macro to check whether `-mindirect-branch=thunk` does actually work, and indeed it does work for that testcase.

But then, I failed to extend that testcase to match the errors below - seems like I couldn't figure out enough details about the breaking symbols to extend the testcase for.

Any idea what might be special to these symbols compared to the testcase in `MV_ADDFLAGS`?

<pre>
x86_64-pc-cygwin-g++ -DSYSCONFDIR=\"/home/haubi/test-20190607/64bit/etc\" -DLOCALEDIR=\"/home/haubi/test-20190607/64bit/usr/share/locale\"  -fdata-sections -ffunction-sections -mindirect-branch=thunk -fcf-protection=full -fstack-clash-protection -D_FORTIFY_SOURCE=2  -O2 -pipe -std=c++14  -Wl,--gc-sections -o eix.exe various/drop_permissions.o eixTk/compare.o eixTk/formated.o eixTk/stringutils.o eixTk/ansicolor.o eixTk/argsreader.o eixTk/parseerror.o eixTk/regexp.o eixTk/sysutils.o eixTk/filenames.o eixTk/utils.o eixTk/varsreader.o database/io.o database/io_header.o database/header.o database/header_portage.o database/io_portage.o database/package_reader.o portage/conf/portagesettings.o portage/conf/cascadingprofile.o eixTk/stringlist.o portage/mask.o portage/mask_list.o portage/depend.o portage/basicversion.o portage/eapi.o portage/extendedversion.o portage/extendedversion_bin.o portage/instversion.o portage/package.o portage/package_best.o portage/packagesets.o portage/vardbpkg.o portage/packagetree.o portage/keywords.o portage/overlay_bin.o portage/overlay.o portage/set_stability.o portage/version.o eixrc/eixrc.o eixrc/global.o eixrc/globals.o eixrc/eixrc_portage.o eixTk/outputstring.o eixTk/stringlist_output.o portage/version_output.o output/formatstring.o output/formatstring-print.o eix.o various/cli.o output/print-xml.o search/levenshtein.o search/algorithms.o search/matchtree.o search/packagetest.o search/packagetest_default.o search/nowarn.o eixTk/ansicolor_print.o eix-diff.o eix-update.o eixTk/percentage.o eixTk/statusline.o cache/cachetable.o cache/common/assign_reader.o cache/common/ebuild_exec.o cache/common/flat_reader.o cache/common/selectors.o cache/base.o cache/eixcache/eixcache.o cache/metadata/metadata.o cache/parse/parse.o cache/sqlite/sqlite.o eixTk/md5.o masked-packages.o versionsort.o eix-header.o eix-drop-permissions.o main/main_all_tools.o cache/cache_map.o            /home/haubi/test-20190607/64bit/usr/lib/libintl.dll.a -L/home/haubi/test-20190607/64bit/usr/lib     
eixTk/argsreader.o:argsreader.cc:(.text$_ZN14ArgumentReader13foldAndRemoveERKSt6vectorI6OptionSaIS1_EE+0xad): relocation truncated to fit: R_X86_64_32S against `.text'
eixTk/varsreader.o:varsreader.cc:(.text$_ZN10VarsReader9EVAL_READEv+0x80): relocation truncated to fit: R_X86_64_32S against `.text'
eixTk/varsreader.o:varsreader.cc:(.text$_ZN10VarsReader16VALUE_WHITESPACEEv+0x3f): relocation truncated to fit: R_X86_64_32S against `.text'
eixTk/varsreader.o:varsreader.cc:(.text$_ZN10VarsReader24VALUE_WHITESPACE_PORTAGEEv+0x3f): relocation truncated to fit: R_X86_64_32S against `.text'
database/package_reader.o:package_reader.cc:(.text$_ZN13PackageReader4readENS_10AttributesE+0x4a): relocation truncated to fit: R_X86_64_32S against `.text'
portage/mask.o:mask.cc:(.text$_ZNK4Mask4testEPK15ExtendedVersion+0xaa): relocation truncated to fit: R_X86_64_32S against `.text'
portage/mask.o:mask.cc:(.text$_ZNK4Mask5applyEP7Versionbj+0x2a): relocation truncated to fit: R_X86_64_32S against `.text'
portage/basicversion.o:basicversion.cc:(.text$_ZlsRSoRK9BasicPart+0x35): relocation truncated to fit: R_X86_64_32S against `.text'
portage/version.o:version.cc:(.text$_ZNK4IUse6prefixEv+0x1f): relocation truncated to fit: R_X86_64_32S against `.text'
portage/version.o:version.cc:(.text$_ZNK4IUse8asStringB5cxx11Ev+0x31): relocation truncated to fit: R_X86_64_32S against `.text'
eixrc/eixrc.o:eixrc.cc:(.text$_ZN5EixRc12dumpDefaultsEP9__sFILE64b+0x150): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1578: eix.exe] Error 1
make[2]: Leaving directory '/home/haubi/test-20190607/64bit/var/tmp/portage/app-portage/eix-0.33.7/work/eix-0.33.7/src'
make[1]: *** [Makefile:521: all-recursive] Error 1
make[1]: Leaving directory '/home/haubi/test-20190607/64bit/var/tmp/portage/app-portage/eix-0.33.7/work/eix-0.33.7'
make: *** [Makefile:441: all] Error 2
</pre>

Using `-Wl,--verbose` to get the `additional relocation overflows omitted from the output` gives these additional errors:

<pre>
eixrc/eixrc.o:eixrc.cc:(.text$_ZN5EixRc12dumpDefaultsEP9__sFILE64b+0x150): relocation truncated to fit: R_X86_64_32S against `.text'
eixrc/eixrc.o:eixrc.cc:(.text$_ZN5EixRc23resolve_delayed_recurseERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt13unordered_setIS5_St4hashIS5_ESt8equal_toIS5_ESaIS5_EESF_PPKcPS5_+0x10f): relocation truncated to fit: R_X86_64_32S against `.text'
eixrc/eixrc.o:eixrc.cc:(.text$_ZN5EixRc23resolve_delayed_recurseERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt13unordered_setIS5_St4hashIS5_ESt8equal_toIS5_ESaIS5_EESF_PPKcPS5_+0x504): relocation truncated to fit: R_X86_64_32S against `.text'
eixTk/outputstring.o:outputstring.cc:(.text$_ZN12OutputString12append_smartEc+0x45): relocation truncated to fit: R_X86_64_32S against `.text'
output/formatstring.o:formatstring.cc:(.text$_ZN12FormatParser5startEPKcbbPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xba): relocation truncated to fit: R_X86_64_32S against `.text'
output/formatstring-print.o:formatstring-print.cc:(.text$_Z25get_diff_package_propertyP12OutputStringPK11PrintFormatPvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1a0): relocation truncated to fit: R_X86_64_32S against `.text'
various/cli.o:cli.cc:(.text$_Z9parse_cliP9MatchTreeP5EixRcP8VarDbPkgP15PortageSettingsPK11PrintFormatPK12SetStabilityPK8DBHeaderPK10ParseErrorPP8MaskListI4MaskERK14ArgumentReader+0xb0): relocation truncated to fit: R_X86_64_32S against `.text'
output/print-xml.o:print-xml.cc:(.text$_ZN8PrintXml5clearEP5EixRc+0x115): relocation truncated to fit: R_X86_64_32S against `.text'
output/print-xml.o:print-xml.cc:(.text$_ZN8PrintXml16escape_xmlstringEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x70): relocation truncated to fit: R_X86_64_32S against `.text'
search/packagetest_default.o:packagetest_default.cc:(.text$_ZN11PackageTest12setAlgorithmENS_14MatchAlgorithmE+0x2b): relocation truncated to fit: R_X86_64_32S against `.text'
eix-header.o:eix-header.cc:(.text$_Z12overlay_loopPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorI13OverlayOptionSaIS7_EE+0xac): relocation truncated to fit: R_X86_64_32S against `.text'
</pre>

**Comment by vaeth** [comment]
Thanks for the report. Since -m*=thunk collides with -fcf-protection=full with gcc-9 anyway, I decided to remove that option completely.
