### ISSUE TITLE
Use more standard --color=always/auto/never option

### ISSUE THREAD

**Issue by pacho2** [vaeth/eix#67]
Hello,

I am used to use --color=always/auto/never switch to allow commands to still print colors when used with a pipe because it looks to be more standard. For example, grep, ls diff... they all use this option.

I think it would be interesting then to use this option to control coloring instead of current eix-specific ones

Thanks a lot

**Comment by vaeth** [comment]
Fixed in 0.33.9_alpha191127.

**Comment by pacho2** [comment]
Thanks!
