### ISSUE TITLE
eix-test-obselete should ignore wildcards

### ISSUE THREAD

**Issue by marcthe12** [vaeth/eix#68]
In order to use the haskell overlay, you usually add a wildcard entry to package.accept_keyword. eix-test-obselete unrolls the wildcard creating several superfluous entries(random haskell pakages i have not installed). Can be a way to handle this use case.

**Comment by vaeth** [comment]
The wildcards *do* create superfluous unmasking and are therefore “redundant” by the strict viewpoint which eix takes by default (if in doubt, things are considered as redundant).

You can say that you do not want to consider any of the entries created by the wildcard as redundant in /etc/portage/package.nowarn:

Create the same wildcard in that file and put into that line the words "no_change in_keywords".
