### ISSUE TITLE
Support for parsing repos.conf

### ISSUE THREAD

**Issue by anthonyryan1** [vaeth/eix#69]
Gentoo recently started the migration of the portage tree from `/usr/portage` to `/var/db/repos/gentoo`.

I recently encountered a bug where eix does not acknowledge this new path, even when it's set in `/etc/portage/repos.conf`

I think going forward, it will be necessary to check the location of the portage tree in this file, rather than assuming `/usr/portage`

**Comment by vaeth** [comment]
Thanks for the report.

`/etc/portage/repos.conf` should work. Is the file/dir (and the parent directories) readable for portage:portage? Maybe you can post this file?

Concerning the fallback, you are right that it should better be configurable than simply /usr/portage. Then the ebuild can adjust it. When I release a new version, I will probably fix it. It is not clear yet when I will find time.

**Comment by vaeth** [comment]
Fixed in v0.33.10.
