### ISSUE TITLE
--installed-with-use usage...

### ISSUE THREAD

**Issue by CaptainBloodz** [vaeth/eix#72]
amd64 ~ # eix --installed-with-use 'python_targets_python_2.7'
No matches found
amd64 ~ # eix --installed-with-use python_targets_python_2.7
No matches found
amd64 ~ # eix kodi -I
[I] media-tv/kodi
     Installed versions:  18.4-r1^t(05:22:35 17/03/2020)(X alsa caps gles opengl system-ffmpeg udev vaapi vdpau xslt -airplay -bluetooth -bluray -cec -css -dbus -dvd -gbm -lcms -libressl -libusb -lirc -mariadb -mysql -nfs -pulseaudio -raspberry-pi -samba -systemd -test -udisks -upnp -upower -wayland -webserver -zeroconf KERNEL="linux" PYTHON_SINGLE_TARGET="python2_7")
     Homepage:            https://kodi.tv/ https://kodi.wiki/
     Description:         A free and open source media-player and entertainment hub

Last output is correct, which the 2 first commands fail to reflect.
What am I doing wrong?

Thks 4 ur attention, interest & support.

**Comment by lkraav** [comment]
eix --installed-with-use 'python_targets_python2_7' or 'python_single_target_python2_7'

**Comment by CaptainBloodz** [comment]
Stupid me!
