### ISSUE TITLE
--proto output has categories without names and only one package per category

### ISSUE THREAD

**Issue by wwjjbb** [vaeth/eix#80]
> $ eix --proto >look.pb

I was trying to figure out why there were >21000 categories in the protocol buffers data when I noticed that none of the categories had names and each category only contained one package.

Happens with versions 0.34.4 to 0.34.10

**Comment by wwjjbb** [comment]
The problem is in the code creating the categories, where its not maintaining the category index very well. its also quite confusing to follow, so here's a simpler version ....

[0001-Fix-proto-output-category-processing.patch.txt](https://github.com/vaeth/eix/files/5454045/0001-Fix-proto-output-category-processing.patch.txt)

**Comment by vaeth** [comment]
Thank you for the report and the fix. The patch has the problem of duplicate lookup which I wanted to avoid. I will try to find a better version. In any case, I will put you to the AUTHORS file.

**Comment by vaeth** [comment]
Fixed in eix-0.34.11
