### ISSUE TITLE
eix -u suddenly started to show masked packages

### ISSUE THREAD

**Issue by baybal** [vaeth/eix#82]
How can I debug this? 

![image](https://user-images.githubusercontent.com/3344988/99908112-d9af4f80-2d0a-11eb-8070-51437f396713.png)

**Comment by vaeth** [comment]
This can have many reasons. What immediately comes to my mind: there might be set ACCEPT_KEYWORDS somewhere or there might be a line like ```*/*``` in package.accept_keywords or paackge.keywords. eix has no particular way to detect the reason.

**Comment by baybal** [comment]
> This can have many reasons. What immediately comes to my mind: there might be set ACCEPT_KEYWORDS somewhere or there might be a line like `*/*` in package.accept_keywords or paackge.keywords. eix has no particular way to detect the reason.

It that was the case, then the emerge would've installed the masked package, but it doesn't

**Comment by baybal** [comment]
As of recent sync, the issue disappeared as mysteriously, as it appeared.
