### ISSUE TITLE
eix-updates shows raw data

### ISSUE THREAD

**Issue by Whissi** [vaeth/eix#83]
Hi,

some packages like [firefox](https://packages.gentoo.org/packages/www-client/firefox), [nodejs](https://packages.gentoo.org/packages/net-libs/nodejs)... have set
```bash
SLOT="0/$(ver_cut 1)"
```
in ebuild. `eix-update` will list them as

```
[U]   == www-client/firefox (84.0.2(0/84)@01/13/2021; (~)84.0.2(0/84) -> (~)85.0_rc1(0/(ver_cut 1))[1]): Firefox Web Browser
                                                                                       ^^^^^^^^^^^
```

**Comment by vaeth** [comment]
Works as intended. You have to generate metadata. See section SPEEDUP in the manpage.
