### ISSUE TITLE
eix --upgrade shows masked package version

### ISSUE THREAD

**Issue by r4rdsn** [vaeth/eix#84]
I don't want to update `=games-action/multimc-0.6.11` from guru overlay so I put this atom in /etc/portage/package.accept_keywords.
```
/etc/portage$ grep -R games-action/multimc
package.accept_keywords/zz-autounmask:=games-action/multimc-0.6.11
```
Portage diligently doesn't update it:
```
/etc/portage$ doas emerge -auDN @world

These are the packages that would be merged, in order:

Calculating dependencies... done!

Nothing to merge; quitting.
```
But eix shows upgrade to 0.6.12:
```
/etc/portage$ eix --upgrade --world
[?] games-action/multimc [1]
     Available versions:  ~0.6.12
     Installed versions:  0.6.11(06:24:34 PM 01/31/2021)
     Homepage:            https://multimc.org https://github.com/MultiMC/MultiMC5
     Description:         An advanced Qt5-based open-source launcher for Minecraft

[1] "guru" /var/db/repos/guru
```
I tried to add `>games-action/multimc-0.6.11` to /etc/portage/package.mask with no luck. How do I remove multimc from list of upgrades?

**Comment by vaeth** [comment]
> [?] games-action/multimc

It is not an upgrade, but a downgrade. Actually it is a broken state: There is no installable version, although you have some installed.

The solution is to fix the state by making sure that the installed version is available. (For instance, put the ebuild in your local overlay and call eix-update afterwards.)
