### ISSUE TITLE
Improve sorting of USE flags containing numbers (such as python_targets_python3_10)

### ISSUE THREAD

**Issue by sbraz** [vaeth/eix#86]
Hi,
At the moment, running `eix -e setuptools` shows `PYTHON_TARGETS="pypy3 python3_10 python3_7 python3_8 python3_9"`.

Could you please look into improving the algorithm to sort those in a more human-friendly way?

Since [the spec](https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-200003.1.4) allows `[A-Za-z0-9+_@-]`, I think the regex `[A-Za-z0-9]+` could define a "word". And if that "word" is numeric, it should be sorted accordingly.

EDIT: actually, maybe any number should be treated specifically so that `version10` comes after `version2`.

[There is a similar bug report for portage itself](https://bugs.gentoo.org/788346).

**Comment by vaeth** [comment]
Solved in eix-0.35.0
