### ISSUE TITLE
eix and terminology's transluciency

### ISSUE THREAD

**Issue by igel-kun** [vaeth/eix#97]
I've recently switched terminal emulators from `rxvt-unicode` to `terminology` and I have transluciency enabled on both.
However, after the switch, I observe that `eix`'s output forces the background to whatever the terminal thinks is black (in my case, opaque, non-translucient black).
That was never an issue with `rxvt-unicode` because I imagine they handle transluciency by just translating the "lightness" of a color to "opacity" but, in `terminology`, when black is not translucient for the terminal, then `eix`'s background will be an opaque, solid black.
A quick and dirty fix is to set `terminology`'s notion of black to something transparent, but I think that's a workaround for the real problem, which is `eix` forcing a black background instead of leaving the default (just like anything else, such as `ls`, really).

**Comment by vaeth** [comment]
Have a look at the eix manpage, in particular "BUGS (and sort of FAQ)" point 2: The configuration
```
BG0=none
BG1=none
BG2=none
BG3=none
```
does what you want. But the colors might then be a bad choice. Therefore I recommend to read also the other remarks in this sectoin.

**Comment by igel-kun** [comment]
Cool, thanks for the hint, that works :)
